from __future__ import annotations

CASES = [
    {
        "id": "en_hot_basic",
        "text": "HOT PREDICTION\nManchester City vs Newcastle\n21 February 2026 | 12:30 UTC\nRECOMMENDATION\nTotal Under 2.5\n@ 2.75",
        "kwargs": {
            "league_label": "Premier League",
            "style_variant": "pro",
            "signal_title": "VALUE CHECK",
            "signal_line_1": "Bookmakers give: 36.4%",
            "signal_line_2": "Our model: 46.2% (+9.9% edge)",
            "league_country": "England",
            "league_round": "Regular Season - 27",
            "venue_name": "Etihad Stadium",
            "venue_city": "Manchester",
            "home_rank": 2,
            "away_rank": 10,
            "home_points": 53,
            "away_points": 36,
            "home_played": 26,
            "away_played": 26,
            "home_goal_diff": 30,
            "away_goal_diff": 0,
            "home_form": "WWDWL",
            "away_form": "WLLLD",
            "home_win_prob": 0.41,
            "draw_prob": 0.27,
            "away_win_prob": 0.32,
        },
    },
    {
        "id": "en_top_long_names",
        "text": "TOP PREDICTION\nNottingham Forest vs Borussia Monchengladbach\n21 February 2026 | 15:00 UTC\nRECOMMENDATION\nTotal Over 2.5\n@ 1.91",
        "kwargs": {
            "league_label": "Premier League",
            "style_variant": "pro",
            "signal_title": "VALUE OVERVIEW",
            "signal_line_1": "Bookmakers give: 47.6%",
            "signal_line_2": "Our model: 69.3% (+21.7% edge)",
            "league_country": "England",
            "league_round": "Regular Season - 27",
            "home_rank": 17,
            "away_rank": 6,
            "home_points": 27,
            "away_points": 42,
            "home_played": 26,
            "away_played": 26,
            "home_goal_diff": -13,
            "away_goal_diff": 6,
            "home_form": "DLDWD",
            "away_form": "DLWLW",
            "home_win_prob": 0.27,
            "draw_prob": 0.32,
            "away_win_prob": 0.41,
        },
    },
    {
        "id": "ru_top_layout",
        "text": "ТОП ПРОГНОЗ\nАстон Вилла vs Лидс\n21 февраля 2026 | 15:00 UTC\nРЕКОМЕНДАЦИЯ\nТотал Больше 2.5\n@ 1.73",
        "kwargs": {
            "league_label": "Premier League",
            "style_variant": "pro",
            "signal_title": "VALUE-БЕТ ИНДИКАТОРЫ",
            "signal_line_1": "Букмекеры дают: 57.8%",
            "signal_line_2": "Наша модель: 64.9% (+7.1% перевес)",
            "league_country": "England",
            "league_round": "Regular Season - 27",
            "home_rank": 3,
            "away_rank": 15,
            "home_points": 50,
            "away_points": 30,
            "home_played": 26,
            "away_played": 26,
            "home_goal_diff": 10,
            "away_goal_diff": -9,
            "home_form": "WDLWL",
            "away_form": "WDLWD",
            "home_win_prob": 0.47,
            "draw_prob": 0.26,
            "away_win_prob": 0.27,
        },
    },
    {
        "id": "en_extreme_odds",
        "text": "HOT PREDICTION\nManchester City vs Newcastle\n21 February 2026 | 12:30 UTC\nRECOMMENDATION\nTotal Under 2.5\n@ 12.38",
        "kwargs": {
            "league_label": "Premier League",
            "style_variant": "pro",
            "signal_title": "VALUE CHECK",
            "signal_line_1": "Bookmakers give: 8.4%",
            "signal_line_2": "Our model: 12.2% (+3.8% edge)",
            "home_rank": 2,
            "away_rank": 10,
            "home_points": 53,
            "away_points": 36,
            "home_played": 26,
            "away_played": 26,
            "home_goal_diff": 30,
            "away_goal_diff": 0,
            "home_form": "WWDWL",
            "away_form": "WLLLD",
            "home_win_prob": 0.12,
            "draw_prob": 0.28,
            "away_win_prob": 0.60,
        },
    },
    {
        "id": "en_no_form",
        "text": "STANDARD PREDICTION\nLecce vs Inter\n22 February 2026 | 14:00 UTC\nRECOMMENDATION\nTotal Over 2.5\n@ 2.10",
        "kwargs": {
            "league_label": "Serie A",
            "style_variant": "pro",
            "signal_title": "VALUE CHECK",
            "signal_line_1": "Bookmakers give: 52.4%",
            "signal_line_2": "Our model: 62.7% (+10.4% edge)",
            "league_country": "Italy",
            "league_round": "Regular Season - 26",
            "home_rank": 17,
            "away_rank": 1,
            "home_points": 24,
            "away_points": 61,
            "home_played": 25,
            "away_played": 25,
            "home_goal_diff": -14,
            "away_goal_diff": 39,
            "home_form": "",
            "away_form": "",
            "home_win_prob": 0.15,
            "draw_prob": 0.27,
            "away_win_prob": 0.58,
        },
    },
    {
        "id": "en_viral_theme",
        "text": "HIGH-CONFIDENCE PICK\nAtalanta vs Napoli\n22 February 2026 | 14:00 UTC\nRECOMMENDATION\nTotal Under 2.5\n@ 2.10",
        "kwargs": {
            "league_label": "Serie A",
            "style_variant": "viral",
            "signal_title": "VALUE SIGNALS",
            "signal_line_1": "Bookmakers give: 47.6%",
            "signal_line_2": "Our model: 69.3% (+21.7% edge)",
            "league_country": "Italy",
            "league_round": "Regular Season - 26",
            "home_rank": 3,
            "away_rank": 2,
            "home_points": 57,
            "away_points": 60,
            "home_played": 25,
            "away_played": 25,
            "home_goal_diff": 21,
            "away_goal_diff": 28,
            "home_form": "WDWWW",
            "away_form": "WWDWW",
            "home_win_prob": 0.33,
            "draw_prob": 0.29,
            "away_win_prob": 0.38,
        },
    },
    {
        "id": "de_long_venue",
        "text": "TOP PREDICTION\nUnion Berlin vs Bayer Leverkusen\n21 February 2026 | 14:30 UTC\nRECOMMENDATION\nTotal Under 2.5\n@ 1.91",
        "kwargs": {
            "league_label": "Bundesliga",
            "style_variant": "pro",
            "signal_title": "VALUE BET INDICATORS",
            "signal_line_1": "Bookmakers give: 36.4%",
            "signal_line_2": "Our model: 53.6% (+17.2% edge)",
            "league_country": "Germany",
            "league_round": "Regular Season - 23",
            "venue_name": "Stadion An Der Alten Forsterei",
            "venue_city": "Berlin",
            "home_rank": 10,
            "away_rank": 6,
            "home_points": 25,
            "away_points": 39,
            "home_played": 22,
            "away_played": 21,
            "home_goal_diff": -9,
            "away_goal_diff": 16,
            "home_form": "LDLLD",
            "away_form": "LWWDW",
            "home_win_prob": 0.27,
            "draw_prob": 0.30,
            "away_win_prob": 0.43,
        },
    },
    {
        "id": "sparse_inputs",
        "text": "HOT PREDICTION\nTeam Alpha vs Team Beta\n21 February 2026 | 12:30 UTC\nRECOMMENDATION\nTotal Under 2.5\n@ 2.30",
        "kwargs": {
            "league_label": "League",
            "style_variant": "pro",
            "signal_title": "VALUE CHECK",
            "signal_line_1": "Bookmakers give: 50.0%",
            "signal_line_2": "Our model: 50.0% (+0.0% edge)",
            "home_win_prob": 0.33,
            "draw_prob": 0.34,
            "away_win_prob": 0.33,
        },
    },
]
